name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Auth to GHCR
        env:
          AUXON_GHCR_TOKEN_RO: ${{ secrets.AUXON_GHCR_TOKEN_RO }}
        run: |
          echo $AUXON_GHCR_TOKEN_RO | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check and lint
        run: |
          cargo check
          cargo clippy

      - name: Integration test
        env:
          MODALITY_LICENSE_KEY: ${{ secrets.MODALITY_LICENSE_KEY }}
        run: |
          cd integration-test
          ./go.sh
